from tkinter import *
cal=Tk()
def minus():
    a=float(ent1.get())
    b=float(ent2.get())
    result.config(text=a-b)
def plus():
    a=float(ent1.get())
    b=float(ent2.get())
    result.config(text=a+b)
def mul():
    a=float(ent1.get())
    b=float(ent2.get())
    result.config(text=a*b)
def div():
    a=float(ent1.get())
    b=float(ent2.get())
    result.config(text=a/b)
cal.geometry('500x500')
label1=Label(cal,text='num1')
label1.pack()
ent1=Entry(cal)
ent1.pack()
label2=Label(cal,text='num2')
label2.pack()
ent2=Entry(cal)
ent2.pack()
but1=Button(cal,text='-',command=minus)
but1.pack()
but2=Button(cal,text='+',command=plus)
but2.pack()
but3=Button(cal,text='*',command=mul)
but3.pack()
but4=Button(cal,text='/',command=div)
but4.pack()
result=Label(cal,text='result')
result.pack()
cal.mainloop()
